@verificationToken={{forgotPassword.response.body.verificationToken}}
@verificationCode=0pV/wHwkcx8=

### Forgot password
# @name forgotPassword

POST {{host}}/auth/forgot-password
Content-Type: application/json

{
    "email": "john@mail.com"
}

### Verify recovery code
# @name verifyRecoveryCode

POST {{host}}/auth/verify-recovery-code
Content-Type: application/json

{
    "verificationToken": "{{verificationToken}}",
    "verificationCode": "{{verificationCode}}"
}

### Change forgotten password
# @name changeForgottenPassword

POST {{host}}/auth/change-forgotten-password
Content-Type: application/json

{
    "verificationToken": "{{verificationToken}}",
    "password": "Password0;"
}