@email=john@mail.com
@refreshTokenCookie= {{login.response.headers.Set-Cookie}}

### Login
# @name login

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "Password0;"
}

### Logout
# @name refresh

POST {{host}}/auth/refresh
Cookie: {{refreshTokenCookie}}
