@verificationToken={{forgotPassword.response.body.verificationToken}}
@verificationCode=vqbuiKOKghs=

### Forgot password
# @name forgotPassword

POST {{host}}/auth/forgot-password
Content-Type: application/json

{
    "email": "john@mail.com"
}

### Verify recovery code
# @name verifyRecoveryCode

POST {{host}}/auth/verify-recovery-code
Content-Type: application/json

{
    "verificationToken": "{{verificationToken}}",
    "verificationCode": "{{verificationCode}}"
}